name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Ensure ssh is installed
      run: sudo apt update; sudo apt -y install openssh-server
      
    - name: Check config
      run: |
        cat > sshd_config <<EOF
          SyslogFacility AUTHPRIV
          PermitRootLogin yes
          AuthorizedKeysFile	.ssh/authorized_keys
          ChallengeResponseAuthentication no
          PubkeyAuthentication yes
        EOF
        cat > ssh_config <<EOF
          StrictHostKeyChecking no
        EOF
        sudo mv sshd_config /etc/ssh/sshd_config
        sudo mv ssh_config /etc/ssh/ssh_config
        sudo systemctl restart ssh
        
    - name: Create ssh key
      run: >
        ssh-keygen -t rsa -f ~/.ssh/id_rsa
        
    - name: Add key to auth file
      run: >
        cat ~/.ssh/id_rsa.pub | tee -a ~/.ssh/authorized_keys
        ssh-add ~/.ssh/id_rsa
        
    - name: Ensure the owner of the key is correct
      run: |
        chmod 600 ~/.ssh/authorized_keys
        chmod 700 ~/.ssh
        sudo chmod -c 0755 ~/
        ls -la ~/.ssh
        
    - name: Go Build
      run: go build -v ./...

    - name: Go Test
      run: go test -v ./...
      
    - name: Check auth.log log on failure
      if: ${{ failure() }}
      run: cat /var/log/auth.log
